/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/shadcn/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    AlertPopup: typeof import('./src/components/shadcn/AlertPopup.vue')['default']
    Build: typeof import('./src/components/Build.vue')['default']
    Button: typeof import('./src/components/shadcn/ui/button/Button.vue')['default']
    Dialog: typeof import('./src/components/shadcn/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/shadcn/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/shadcn/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/shadcn/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/shadcn/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/shadcn/ui/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/shadcn/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/shadcn/ui/dialog/DialogTrigger.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemPicker: typeof import('./src/components/ItemPicker.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiMinus: typeof import('~icons/mdi/minus')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiReload: typeof import('~icons/mdi/reload')['default']
    MdiTrash: typeof import('~icons/mdi/trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./src/components/Stats.vue')['default']
    Toast: typeof import('./src/components/shadcn/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/shadcn/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/shadcn/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/shadcn/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/shadcn/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/shadcn/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/shadcn/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/shadcn/ui/toast/ToastViewport.vue')['default']
    Traits: typeof import('./src/components/Traits.vue')['default']
  }
}
